parameters:
#    pecserke_twig_doctrine_loader.example.class: Pecserke\Bundle\TwigDoctrineLoaderBundle\Example

services:
#    pecserke_twig_doctrine_loader.example:
#        class: %pecserke_twig_doctrine_loader.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
